"""Add dates

Revision ID: 0866bcd2f0a6
Revises: 8b9b3d382364
Create Date: 2019-02-11 10:08:49.157790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0866bcd2f0a6'
down_revision = '8b9b3d382364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('deployment', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment', 'updated')
    op.drop_column('deployment', 'created')
    # ### end Alembic commands ###
