"""Update Deployment and DeploymentTarget tables.

Revision ID: 3646db1b8453
Revises: dac2243ad0ba
Create Date: 2021-11-15 15:27:51.889305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3646db1b8453'
down_revision = 'dac2243ad0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('deployment_target', sa.Column('namespace', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment_target', 'namespace')
    op.drop_column('deployment', 'name')
    # ### end Alembic commands ###
