"""Traceability

Revision ID: 58972ff6114b
Revises: bd363a0d9bb4
Create Date: 2019-06-24 10:05:58.201818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58972ff6114b'
down_revision = 'bd363a0d9bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traceability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('DATA_SOURCE', 'WORKFLOW', 'JOB', 'DEPLOYMENT', 'MODEL', name='AuditableTypeEnumType'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('DATA_SOURCE', 'WORKFLOW', 'JOB', 'DEPLOYMENT', 'MODEL', name='AuditableTypeEnumType'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('context', sa.String(length=100), nullable=False),
    sa.Column('module', sa.Enum('PEEL', 'JUICER', 'LIMONERO', 'CITRUS', 'SEED', 'STAND', 'TAHITI', name='ModuleTypeEnumType'), nullable=False),
    sa.Column('action', sa.Enum('UNDEPLOY', 'DISPLAY_DATA', 'DEPLOY', 'SAVE_DATA', 'INFER_SCHEMA', 'DISPLAY_SCHEMA', 'SAVE_VISUALIZATION', 'CREATE_MODEL', 'APPLY_MODEL', name='ActionTypeEnumType'), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('workflow_name', sa.String(length=250), nullable=True),
    sa.Column('task_id', sa.String(length=200), nullable=True),
    sa.Column('task_name', sa.String(length=200), nullable=True),
    sa.Column('task_type', sa.String(length=200), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('deployment', 'image_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('deployment', 'target_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployment', 'target_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('deployment', 'image_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_table('traceability')
    # ### end Alembic commands ###
