"""Metric

Revision ID: 6b631acda388
Revises: 58972ff6114b
Create Date: 2019-10-28 15:44:27.999636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b631acda388'
down_revision = '58972ff6114b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_time', sa.DateTime(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('probe_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('data', mysql.LONGTEXT(), nullable=False),
    sa.Column('tma_data', mysql.LONGTEXT(), nullable=True),
    sa.Column('item', sa.String(length=200), nullable=True),
    sa.Column('sent', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_value')
    # ### end Alembic commands ###
