"""empty message

Revision ID: 77c18eec4020
Revises: 
Create Date: 2018-07-30 16:20:47.814052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77c18eec4020'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE DATABASE IF NOT EXISTS seed;")
    op.create_table('deployment_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('authentication_info', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('target_type', sa.Enum('SUPERVISOR', 'KUBERNETES', 'DOCKER', 'MARATHON', name='DeploymentTypeEnumType'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=100), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('current_status',
              sa.Enum('RUNNING', 'SUSPENDED', 'STOPPED' 'SAVED', 'EDITING', 'PENDING', 'ERROR', 'DEPLOYED',
                      name='DeploymentStatusEnumType'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('log', mysql.LONGTEXT(), nullable=True),
    sa.Column('entry_point', sa.String(length=800), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['deployment_image.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['deployment_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    op.drop_table('deployment')
    op.drop_table('deployment_target')
    op.drop_table('deployment_image')
    # ### end Alembic commands ###
