"""Add workflow name

Revision ID: 7b884dec107f
Revises: 0866bcd2f0a6
Create Date: 2019-02-11 10:28:48.843267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b884dec107f'
down_revision = '0866bcd2f0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('workflow_name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment', 'workflow_name')
    # ### end Alembic commands ###
