"""job_id

Revision ID: 9da91a3b53d8
Revises: 7b884dec107f
Create Date: 2019-02-11 22:28:48.581006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da91a3b53d8'
down_revision = '7b884dec107f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('job_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment', 'job_id')
    # ### end Alembic commands ###
