"""Reviewing models

Revision ID: be218984140b
Revises: 39b9201e2b1c
Create Date: 2019-04-04 09:03:02.063585

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.mysql import LONGTEXT

# revision identifiers, used by Alembic.
revision = 'be218984140b'
down_revision = '39b9201e2b1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('status',
                              sa.Enum('RUNNING', 'SUSPENDED', 'STOPPED' 'SAVED',
                                      'EDITING', 'PENDING', 'ERROR', 'DEPLOYED',
                                      name='DeploymentStatusEnumType'),
                              nullable=False),
                    sa.Column('log', LONGTEXT,
                              nullable=False),
                    sa.Column('deployment_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['deployment_id'],
                                            ['deployment.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('deployment_metric',
                  sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('deployment_metric',
                  sa.Column('user_login', sa.String(length=100),
                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment_metric', 'user_login')
    op.drop_column('deployment_metric', 'user_id')
    op.drop_table('deployment_log')
    # ### end Alembic commands ###
