"""Update Deployment and DeploymentTarget.

Revision ID: f33bb6218ccd
Revises: cbf95b5e48c7
Create Date: 2021-11-22 10:39:23.184958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f33bb6218ccd'
down_revision = 'cbf95b5e48c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('port', sa.String(length=10), nullable=True))
    op.add_column('deployment', sa.Column('assets', mysql.LONGTEXT(), nullable=True))
    op.add_column('deployment_target', sa.Column('target_port', sa.String(length=10), nullable=False))
    op.add_column('deployment_target', sa.Column('volume_path', mysql.LONGTEXT(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment_target', 'volume_path')
    op.drop_column('deployment_target', 'target_port')
    op.drop_column('deployment', 'assets')
    op.drop_column('deployment', 'port')
    # ### end Alembic commands ###
