# coding=utf-8
"""
Flask application for deploying a Lemonade workflow in production.
This file is generated.
DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

(c) 2016-2019   Lemonade Project - Universidade Federal de Minas Gerais
                Departamento de Ciência da Computação
                Laboratório e-Speed

http://www.lemonade.org.br
"""
from flask import Flask

app = Flask(__name__)


@app.route('/')
def service():
    return 'Hello, World!'
