"""empty message

Revision ID: 10120f95d77f
Revises: 0707db05a85f
Create Date: 2020-06-15 18:05:38.563437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from thorn.migration_utils import is_psql, is_sqlite

# revision identifiers, used by Alembic.
revision = '10120f95d77f'
down_revision = '0707db05a85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'DELETED', name='NotificationStatusEnumType'), nullable=False),
    sa.Column('from_system', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'ERROR', name='NotificationTypeEnumType'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_notification_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('configuration_translation', sa.Column('category', sa.Unicode(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('configuration_translation') as batch_op:
            batch_op.drop_column('category')
    else:
        op.drop_column('configuration_translation', 'category')
    op.drop_table('notification')

    if is_psql():
        op.get_bind().execute('DROP TYPE "NotificationStatusEnumType"')
        op.get_bind().execute('DROP TYPE "NotificationTypeEnumType"')
    # ### end Alembic commands ###
