"""empty message

Revision ID: 1fbc565aa957
Revises: 731386923937
Create Date: 2021-07-15 14:37:24.527713

"""
from alembic import op
import sqlalchemy as sa
from thorn.migration_utils import is_sqlite

# revision identifiers, used by Alembic.
revision = '1fbc565aa957'
down_revision = '731386923937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not is_sqlite():
        op.create_index(op.f('ix_user_workspace_id'), 'user', ['workspace_id'], unique=False)
        op.create_foreign_key('fk_user_workspace_id', 'user', 'workspace', ['workspace_id'], ['id'], use_alter=True)
        op.create_index(op.f('ix_user_preference_user_id'), 'user_preference', ['user_id'], unique=False)
        op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
        op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
        op.create_index(op.f('ix_workspace_owner_id'), 'workspace', ['owner_id'], unique=False)
        op.create_foreign_key('fk_workspace_owner_id', 'workspace', 'user', ['owner_id'], ['id'])
    else:
        with op.batch_alter_table('user') as batch_op:
            batch_op.create_index(op.f('ix_user_workspace_id'), ['workspace_id'], unique=False)
            batch_op.create_foreign_key('fk_user_workspace_id', 'workspace', ['workspace_id'], ['id'], use_alter=True)
        with op.batch_alter_table('user_preference') as batch_op:
            batch_op.create_index(op.f('ix_user_preference_user_id'), ['user_id'], unique=False)
        with op.batch_alter_table('user_role') as batch_op:
            batch_op.create_index(op.f('ix_user_role_role_id'), ['role_id'], unique=False)
            batch_op.create_index(op.f('ix_user_role_user_id'), ['user_id'], unique=False)
        with op.batch_alter_table('workspace') as batch_op:
            batch_op.create_index(op.f('ix_workspace_owner_id'), ['owner_id'], unique=False)
            batch_op.create_foreign_key('fk_workspace_owner_id', 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not is_sqlite():
        op.drop_constraint('fk_workspace_owner_id', 'workspace', type_='foreignkey')
        op.drop_index(op.f('ix_workspace_owner_id'), table_name='workspace')
        op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
        op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
        op.drop_index(op.f('ix_user_preference_user_id'), table_name='user_preference')
        op.drop_constraint('fk_user_workspace_id', 'user', type_='foreignkey')
        op.drop_index(op.f('ix_user_workspace_id'), table_name='user')
    else:
        with op.batch_alter_table('user') as batch_op:
            batch_op.drop_constraint('fk_user_workspace_id')
            batch_op.drop_index(op.f('ix_user_workspace_id'))
        with op.batch_alter_table('user_preference') as batch_op:
            batch_op.drop_index(op.f('ix_user_preference_user_id'))
        with op.batch_alter_table('user_role') as batch_op:
            batch_op.drop_index(op.f('ix_user_role_role_id'))
            batch_op.drop_index(op.f('ix_user_role_user_id'))
        with op.batch_alter_table('workspace') as batch_op:
            batch_op.drop_index(op.f('ix_workspace_owner_id'))
            batch_op.drop_constraint('fk_workspace_owner_id')

 
   # ### end Alembic commands ###
