"""Role permission

Revision ID: 2f93dbc61a5d
Revises: 1fba1a39c681
Create Date: 2020-03-03 10:49:02.405503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from thorn.migration_utils import is_sqlite

# revision identifiers, used by Alembic.
revision = '2f93dbc61a5d'
down_revision = '9218f15233f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('target', sa.String(length=1000), nullable=False),
    sa.Column('allowed_methods', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managed_resource_role',
    sa.Column('managed_resource_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['managed_resource_id'], ['managed_resource.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )

    if is_sqlite():
        with op.batch_alter_table('role_translation') as batch_op:
            batch_op.alter_column('description', nullable=True)
    else:
        op.alter_column('role_translation', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('role_translation') as batch_op:
            batch_op.alter_column('description', nullable=False, server_default='')
    else:
        op.alter_column('role_translation', 'description',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_table('role_permission')
    op.drop_table('managed_resource_role')
    op.drop_table('managed_resource')
    # ### end Alembic commands ###
