"""empty message

Revision ID: 301419649460
Revises: 9c908beaa51a
Create Date: 2020-06-23 22:53:32.662141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from thorn.migration_utils import is_mysql

# revision identifiers, used by Alembic.
revision = '301419649460'
down_revision = '9c908beaa51a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', mysql.LONGTEXT() if is_mysql() else sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_preference_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preference')
    # ### end Alembic commands ###
