"""empty message

Revision ID: 6691e9f3ee37
Revises: 301419649460
Create Date: 2020-07-16 22:10:45.538728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from thorn.migration_utils import is_sqlite

# revision identifiers, used by Alembic.
revision = '6691e9f3ee37'
down_revision = '301419649460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('text', sa.String(length=2000), nullable=False, 
        server_default=''))
    op.add_column('notification', sa.Column('link', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('notification') as batch_op:
            batch_op.drop_column('text')
            batch_op.drop_column('link')
    else:
        op.drop_column('notification', 'text')
        op.drop_column('notification', 'link')
    # ### end Alembic commands ###
