"""adjusts

Revision ID: 9429d9e2ef7f
Revises: 0ee1a7bbcf93
Create Date: 2020-04-01 09:21:11.303046

"""
from alembic import op
import sqlalchemy as sa
from thorn.migration_utils import is_sqlite


# revision identifiers, used by Alembic.
revision = '9429d9e2ef7f'
down_revision = '0ee1a7bbcf93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('system', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if is_sqlite():
        with op.batch_alter_table('role') as batch_op:
            batch_op.drop_column('system')
    else:
        op.drop_column('role', 'system')
    # ### end Alembic commands ###
